### ISSUE TITLE
A way to serialize/deserialize a graph easily

### ISSUE THREAD

**Issue by ruggertech** [mhelvens/graph.js#22]
Is there a way to serialize/save the graph so that it could easily be deserialized/loaded ?

**Comment by mhelvens** [comment]
Good question. I should definitely implement a `.toJSON` method for these graphs. I'll try to do it this week.

If you're in a hurry, it'll be easy enough to do manually. A graph consists entirely of its set of vertices and its set of edges. Each vertex has a key and a value. Each edge has two keys and a value. You could serialize like this:

`````javascript
let str = JSON.stringify({
    vertices: [...graph.vertices()],
    edges:    [...graph.edges()]
});
`````

And deserialize like this:

`````javascript
let {vertices, edges} = JSON.parse(str);
let graph = new Graph(vertices);
for (let edge of edges) { graph.addNewEdge(...edge) }
`````

This is probably how it'll be implemented, but I'll want to write a bunch of tests to be sure.

Note that although vertices can be passed to the constructor directly, this is not currently true for the edges because of a stupid design decision I made early on, which will be fixed in the next major version of the library (#6).

**Comment by mhelvens** [comment]
I had an extra hour, so I added the instance method `.toJSON()` and the static method `.fromJSON()`. Check out version 1.21.1. Let me know whether it's working for you!
